import { NextApiRequest, NextApiResponse } from "next";                                                                                                                                                                                         
import fs from "fs";                                                                                                                                                                                                                            
import path from "path";                                                                                                                                                                                                                        
import { IncomingForm } from "formidable";                                                                                                                                                                                                      
                                                                                                                                                                                                                                                
const handler = async (req, res) => {                                                                                                                                                                                                           
  if (req.method === "POST") {                                                                                                                                                                                                                  
    const form = new IncomingForm();                                                                                                                                                                                                            
    form.parse(req, async (err, fields, files) => {                                                                                                                                                                                             
      console.log("\n\n\n\n\n\n🚀 ~ file: upload.js:10 ~ form.parse ~ err, fields, files:", err, fields, files)
      if (err) {                                                                                                                                                                                                                                
        res.status(500).json({ message: "Error processing the request" });                                                                                                                                                                      
        return;                                                                                                                                                                                                                                 
      }                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                
      const file = files.file;                                                                                                                                                                                                                  
      console.log("🚀 ~ file: upload.js:17 ~ form.parse ~ file:", file)
      const fileExtension = path.extname(file.name).toLowerCase();                                                                                                                                                                              
      const isImage = [".jpg", ".jpeg", ".png", ".gif"].includes(fileExtension);                                                                                                                                                                
      const isVideo = [".mp4", ".webm", ".ogg"].includes(fileExtension);                                                                                                                                                                        
                                                                                                                                                                                                                                                
      if (!isImage && !isVideo) {                                                                                                                                                                                                               
        res.status(400).json({ message: "Invalid file type" });                                                                                                                                                                                 
        return;                                                                                                                                                                                                                                 
      }                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                
      const targetDirectory = isImage                                                                                                                                                                                                           
        ? "nodejs/assets/images"                                                                                                                                                                                                                
        : "nodejs/assets/videos";                                                                                                                                                                                                               
      const targetPath = path.join(targetDirectory, file.name);                                                                                                                                                                                 
                                                                                                                                                                                                                                                
      fs.rename(file.path, targetPath, (err) => {                                                                                                                                                                                               
        if (err) {                                                                                                                                                                                                                              
          res.status(500).json({ message: "Error saving the file" });                                                                                                                                                                           
          return;                                                                                                                                                                                                                               
        }                                                                                                                                                                                                                                       
        res.status(200).json({ message: "File uploaded successfully" });                                                                                                                                                                        
      });                                                                                                                                                                                                                                       
    });                                                                                                                                                                                                                                         
  } else {                                                                                                                                                                                                                                      
    res.status(405).json({ message: "Method not allowed" });                                                                                                                                                                                    
  }                                                                                                                                                                                                                                             
};                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                
export default handler; 